project:
  type: book
  output-dir: docs

book:
  title: "Methods for estimating Reproduction Number, R(t)"
  author:
    - name: Chad Milando
      email: cmilando@bu.edu
      degrees: PhD
      attributes:
        corresponding: true
      affiliations:
        - Boston University, School of Public Health
    - name: Laura White
      degrees: PhD
      affiliations:
        - Boston University, School of Public Health


  date: "2/14/2025"
  chapters:
    - index.qmd
    - introduction.qmd
    - decisiontree.qmd
    - part: packages.qmd
      chapters:
      - package_EpiNow2.qmd
      - package_EpiEstim.qmd
      - package_RtEstim.qmd
    - part: methods.qmd
      chapters:
        - method_fixedwindow.qmd
    - references.qmd

bibliography: references.bib
csl: nature.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: cover.png



